export const FETCH_CITIES = 'FETCH_CITIES';
export const NEW_CITY = 'NEW_CITY';
export const FETCH_ITINERARIES = 'FETCH_ITINERARIES';
export const NEW_ITINERARY = 'NEW_ITINERARY';
export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const NEW_ACTIVITY = 'NEW_ACTIVITY';